### ISSUE TITLE
node-sass is out of date

### ISSUE THREAD

**Issue by peterhughesdev** [keystonejs/generator-keystone#100]
The version of node-sass that is used is one major release behind. The version used (at the time of writing) contains a bug where running in production environment causes sass files to be compressed without media-query bodies. This breaks bootstrap's grid layout as well as user-land styles.

Ideally this should use the latest (2.1.1). This also requires bumping node-sass-middleware to 0.5.0

**Comment by Zerim** [comment]
Just ran into some minor problems as a result of this as well and took some time to realize I need to upgrade the node-sass and node-sass-middleware modules.

The version of node-sass being used has a bug where CSS color names i.e. "white" "red", etc. or not computed when defining SASS variables.

i.e.
In version used by keystone-generator...

    $default-color: white; //will not be computed
    $default-color: #ffffff; //works


In latest version of node-sass and node-sass-middleware

    $default-color: white; //works
    $default-color: #ffffff; //works

I should note that I was able to update to latest versions without any complications.

**Comment by JedWatson** [comment]
I've released a new version of the generator with all dependencies updated, sass seems to work correctly again now.
