### ISSUE TITLE
Upon initial project setup gulp lint throws warnings

### ISSUE THREAD

**Issue by mikeLspohn** [keystonejs/generator-keystone#104]
There are warnings in all the models files using default when it's a reserved word. In email.js route enquiry_url is not in camel case warning. Also a bunch of the not camel case warning in keystone.js. I don't think the code is really wrong by style choice so maybe the jshint that gulp is using needs to change up the jshintrc.

**Comment by mikeLspohn** [comment]
After changing the es3 to false and ignoring the camel_case no more warning are present. Can/Shold this change be made to the jshintrc included with the generator?

**Comment by morenoh149** [comment]
@mikeLspohn that's probably the easiest solution. But I think the better solution is to change the code to conform to the default jshint rules.

**Comment by mikeLspohn** [comment]
I agree It would be better! I just figured for a personal project changing j shintrc was a suitable fix.

**Comment by morenoh149** [comment]
indeed. But the issue tracker is for the community project. I'll make this as todo.

**Comment by JedWatson** [comment]
We've removed .jshintrc from the generator, it'll be replaced with eslint which is more a standard thing now. The code should pass out of the box, so I'm closing this now. Thanks for the report!
