### ISSUE TITLE
Gruntfile will always be sass

### ISSUE THREAD

**Issue by sphvn** [keystonejs/generator-keystone#107]
Obviously if you choose `less` in the generator it should setup the `Gruntfile.js` to use `less` not `sass`.

This is obviously because it's hard coded in `templates/grunt`

**Comment by morenoh149** [comment]
so we need a `less.js` file at https://github.com/keystonejs/generator-keystone/tree/master/app/templates/grunt @sphvn mind adding one

**Comment by sphvn** [comment]
I'm rather busy at the moment but will look at issuing a PR when I get a moment.

**Comment by Noviny** [comment]
We are removing grunt from the generator for the next release, so this issue is no longer relevant. Closing.
