### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by sylvainlap** [keystonejs/generator-keystone#110]
Email templates are not in the correct subfolder.

Instead of being copied in `templates/emails/enquiry-notification.ext`, shouldn't they be in `templates/emails/enquiry-notification/email.ext` ?

**Comment by morenoh149** [comment]
`templates/emails/enquiery-notification/` is the correct directory according to whom? mandrill documentation?

**Comment by Noviny** [comment]
Closing this issue as we clear up the issue tracker.

We are comfortable with the current way of structuring these directories, so aren't looking to make this change.
