### ISSUE TITLE
[nodemon] watching 31,640 files - this might cause high cpu usage. To reduce use "--watch"

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/generator-keystone#111]
What config file changes would be necessary to exclude the node-modules directory?  Maybe this generator should also consider such a config by default?

**Comment by morenoh149** [comment]
From skimming https://github.com/keystonejs/generator-keystone/blob/d4ed2820de7ce327e48bc142a7118d9a8b223e7e/app/templates/Gruntfile.js and https://github.com/keystonejs/generator-keystone/blob/efe09d1e9c457781fe20c7f3f179e094ccd1051a/app/templates/_package.json looks like grunt uses [grunt-contrib-watch](https://www.npmjs.com/package/grunt-contrib-watch) to watch files.

Additionally it looks like nowhere do we declare the `watch` task. We are simply using the default command.

I would suggesting reading the docs for grunt-contrib-watch and put an explicit definition for the `watch` task in the gruntfile that ignore the right folders. Then contribute that upstream.
