### ISSUE TITLE
generator-keystone installs but yo doesn't see it.

### ISSUE THREAD

**Issue by ogrotten** [keystonejs/generator-keystone#115]
installation output: https://gist.github.com/ogrotten/9aad70bf84bf669a2edc

I'd origianlly had a problem using the install instructions on keystonejs.com... a permissions error with `spawn-sync` (an upline dependency). Once that was fixed I had this problem, and came over here in the hopes that I could bypass the problem with a more manual installation. (Note: I came to realize it's not anymore manual.)

The installation doesn't error anymore, as shown on the above gist. Yeoman just doesn't see it.

**Comment by jeffreypriebe** [comment]
Seems like this is often a path issue. That yeoman reports "0" registered generators further hints at that being the issue.

Start with "yo doctor" and then follow the instructions for anything it reports as a problem.

See also: http://stackoverflow.com/a/21066014/1592

**Comment by morenoh149** [comment]
@ogrotten reopen if the you're still seeing this issue
