### ISSUE TITLE
Prompt for mongodb URI or check mongo availability

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/generator-keystone#12]
As pointed out by @subhog in JedWatson/keystone#272, `yo keystone` should prompt for the default mongodb connection URI and if it's local, check that the mongod process is running before it completes.

If the mongo connection is not available, it should include instructions to start it before the 'start your app with `node keystone` line.

**Comment by Noviny** [comment]
Cleaning old issues from the issue tracker, so closing this.

May revisit later.
