### ISSUE TITLE
node keystone command throws error after installing on Mac OSX Yosemite

### ISSUE THREAD

**Issue by tejokumar** [keystonejs/generator-keystone#129]
I have created keystone project with default options by running `yo keystone`. Project is created without any errors. When I run `node kestone`, I get following error.

```
MYSYSTEM:my-site myusername$ node keystone
module.js:338
    throw err;
          ^
Error: Cannot find module 'unicode/category/So'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at symbols (/Users/myusername/github/myweb/my-site/node_modules/keystone/node_modules/keystone-utils/node_modules/slug/slug.js:6:16)
    at /Users/myusername/github/myweb/my-site/node_modules/keystone/node_modules/keystone-utils/node_modules/slug/slug.js:199:5
    at Object.<anonymous> (/Users/myusername/github/myweb/my-site/node_modules/keystone/node_modules/keystone-utils/node_modules/slug/slug.js:212:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I am using node - v0.12.7, npm -2.11.3

**Comment by morenoh149** [comment]
try node 4.0 or later

**Comment by nardelli** [comment]
I get the same error. Ubuntu 14.04 x64 running on Digital Ocean. Node v4.1.1, npm 2.14.4.

I've tried `sudo node keystone`, also `npm cache clean`. Seems i'm getting many issues with the node_modules. Am i on too new a version of npm or node?

**Comment by priom** [comment]
getting the same error..can't get it fixed...installed unicode manually...did npm cache clean and sudo npm...still same error!!! and I'm running all the version of all frameworks

**Comment by priom** [comment]
okay..I just fixed mine..I remove unicode and slug modules manually from node_modules...and then reinstalled just slug with npm install slug...and it worked finally!!!!

**Comment by morenoh149** [comment]
@priom do you know what the problem was exactly? so we can fix it for others.

**Comment by terenzeyuen** [comment]
Having the same issue...removing slug and unicode and run npm install slug worked.

**Comment by ppiekarczyk** [comment]
Take a look at this package.
https://github.com/dodo/node-unicodetable

running `apt-get install unicode` followed by `npm install` will take care of the issue.

**Comment by priom** [comment]
@morenoh149 hey..the slug version comes with the package might be deprecated which was causing all this issue...

**Comment by morenoh149** [comment]
which slug dependency?

**Comment by erg0dic** [comment]
I also have this issue:
```
rcj@mcdouble:keystonejs-1865 $ node -v
v4.2.0
rcj@mcdouble:keystonejs-1865 $ npm -v
3.5.0
```

It looks like postinstall script from node-unicodetable is not running?

If I manually run:
```
node node_modules/unicode/install.js
```

then I can run ``node keystone`` without errors

**Comment by morenoh149** [comment]
hmm does https://github.com/dodo/node-unicodetable/blob/master/package.json#L13 look right? maybe it should be `"postinstall": "install.js",` https://docs.npmjs.com/misc/scripts#examples

**Comment by TheRoadSouth** [comment]
Same here, as mentioned above, removing the slug and unicode modules manually and running npm install slug worked.

**Comment by ghoshbinayak** [comment]
While installing the `unicode` module the `install.sh` tried to find the `UnicodeData.txt` file but failed. It also tried to download it but that didn't work for some reason. So I manually downloaded the `UnicodeData.txt` file put in the path it was looking for and then ran the `install.sh` script again. This generated the required `So` files and the problem was fixed.

**Comment by telekosmos** [comment]
That is the solution worked for me! (using node v4.2.2 and npm 3.5.3). Just say that the right paths to store the file can be found in the [unicode repo](https://github.com/dodo/node-unicodetable) (exactly in [`install.js`](https://github.com/dodo/node-unicodetable/blob/master/install.js) file). 
Hope it helps.

**Comment by r3wt** [comment]
fyi, this solution works on debian. same problem.

**Comment by HughGrant** [comment]
same here on windows 7, with NODE 6.2

**Comment by rajendrakhabiyagate6** [comment]
If you are facing this issue and you are behind windows please follow below steps, i hope worked for you :

 1. Remove the unicode module using npm, npm remove unicode
 2. Downloaded the file from
    http://unicode.org/Public/UNIDATA/UnicodeData.txt and placed it into
    C:\usr\share\unicode-data\ if your project is in C drive, or if you are using
    linux place it in /usr/share/unicode or /usr/share/unicode-data 
 3. Installed unicode again

**Comment by rajendrakhabiyagate6** [comment]
If you are facing this issue and you are behind windows please follow below steps, i hope worked for you :

 1. Remove the unicode module using npm, npm remove unicode
 2. Downloaded the file from
    http://unicode.org/Public/UNIDATA/UnicodeData.txt and placed it into
    C:\usr\share\unicode-data\ if your project is in C drive, or if you are using
    linux place it in /usr/share/unicode or /usr/share/unicode-data 
 3. Installed unicode again

**Comment by Noviny** [comment]
This issue has been resolved in Keystone itself for v4, which we are upgrading the generator to now.

If anyone is still experiencing after this, please reopen the issue.
