### ISSUE TITLE
Fix Stylus support

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/generator-keystone#134]
Ref https://github.com/keystonejs/keystone/issues/1759
"No site.css file gets generated when running Keystone, just a 'public/styles/site.styl' file. Also Bootstrap remains enabled but as far as I'm aware, Bootstrap and Stylus are not compatible."

**Comment by jkallunki** [comment]
This would do the actual work: https://github.com/keystonejs/keystone/pull/2061
Still need to submit a modification to the generator where Stylus will be added as a dependency to the generated project.

**Comment by FrankyYang** [comment]
mark, same problem, searching solutions...

**Comment by pll33** [comment]
Should this be closed after #149 was merged?

**Comment by morenoh149** [comment]
I think the desire is to get keystone core to parse stylus files same as sass files via sass-middleware. So far only the gulp tasks for compiling stylus are floating around.

**Comment by morenoh149** [comment]
I think so.
