### ISSUE TITLE
will it ever work on WINDOWS 10 ? Help

### ISSUE THREAD

**Issue by djholly123** [keystonejs/generator-keystone#135]
loads of errors

windows 10,
VS 2010 installed
node 4.2.1

and  tried npm /  npm3

any ides on true steps

**Comment by djholly123** [comment]
after installing VCExpress Desktop i get rid of node-gyp errors when npm install with --msvs_version=2015

But still get this error ... getting tedious

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
D:\key2\key2\node_modules\keystone\lib\core\mount.js:327
                                throw e;
                                ^

**Comment by internetErik** [comment]
Are you running a local mongo instance?

**Comment by djholly123** [comment]
yes

**Comment by djholly123** [comment]
mongodb is running on default port localhost and connects ok from robomongo

now tried remove Python, node, remove all shared modules full reinstall of PYTHON / node x64 and ...

(all as administrator no UAC)

npm install -g npm (no errors)
npm install -g yo --msvs_version=2015 (no errors)
npm install -g generator-keystone --msvs_version=2015

NOW GET THIS ERROR form generator :

npm WARN EPEERINVALID generator-keystone@0.3.9 requires a peer of yo@>=1.0.0 but
 none was installed.
npm ERR! code 1

any ideas appreciated ?

**Comment by djholly123** [comment]
had success installing the demo app was able to start

generator is still not working on windows

**Comment by KuroTsuto** [comment]
The `bson` error is not generated from `generator-keystone` but rather `keystone` itself as a result of nested `mongoose` 3 dependencies - this error has been resolved in the Keystone 0.4.x alpha. See KeystoneJS issues [#959](https://github.com/keystonejs/keystone/issues/959) and duplicates [#1752](https://github.com/keystonejs/keystone/issues/1752) and [#1942](https://github.com/keystonejs/keystone/issues/1942).

The `npm WARN EPEERINVALID` **warning** regarding a `yo` PeerDependency has been resolved with PR #143.

Both issues are effectively warnings and neither interferes with the installation nor execution of a Keystone site.

Any further problems you might be experiencing are most likely the product of the complications surrounding the `node-gyp` build environment on Windows 10, and are thus not something that can be fixed within the `keystone-generator` code-base. Keep an eye on `node-gyp` issue [#629](https://github.com/nodejs/node-gyp/issues/629) for updates and resolution.

**Comment by Noviny** [comment]
We've upgraded the generator to use Keystone 4.0, which should resolve this issue.

Feel free to reopen or comment if you are still experiencing this.
