### ISSUE TITLE
Work out a better way to keep packages up to date

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/generator-keystone#142]
As discussed in keystonejs/keystone#1927 with @adnasa and @ericelliott -

Keeping the package dependencies up to date at the moment involves a very manual process of actually generating projects then checking for updates in them (I use [ncu](https://www.npmjs.com/package/npm-check-updates))

Wondering if there are any better ideas, if there's a package out there that would help,  or if someone's interested in writing a custom script that checks for updates to _all_ the possible dependencies in the package.json template.

Updating dependencies also involves testing not just the generator but the projects that are created, which is currently not a thing, so ideas for how to do that in an automated way need to factor into the solution.

**Comment by ericelliott** [comment]
Ideally, testing projects will mean:

1. Unit testing Keystone plugins
2. Functional testing for the running project app

IMO, Keystone should not concern itself with either of those, but Keystone could make it very simple to traverse through plugins and run the unit tests for each.

Am I on the right track?

**Comment by adnasa** [comment]
I don't know how this is related to what @JedWatson is into, since this issue is more about keeping packages for the keystone project up to date, not testing them.

---

I do feel that it is the maintainer's responsibility to keep them up to date. What I meant to convery with my question on that PR is that we should keep it in mind to keep them updated on both.

Jed, is it "a lot of work" doing it manually? I can agree that ideally there should be an automation (either through a custom script or..) as for 3rd package, I can't think of something on the top of my head.

**Comment by morenoh149** [comment]
@adnasa the way I read it, we would write a suite that would run the generator to make a sample keystone site. Then run some e2e tests on the site and if those pass then the dependency change is good to go.

**Comment by joggienl** [comment]
Interesting... for already scaffold-ed projects ncu is nice and helpfull. Would keep that!

For this generator, maybe in general, it is not bad to always use the latest versions of (dev)dependencies in your project? As an example i've put an alternate _package.json and a function one should add to the app/index.js file..

https://gist.github.com/joggienl/a70e54e811e184c70667e37a27b9a44d

The idea is that you let yeoman install the packages through the npmInstall function as described here http://yeoman.io/generator/actions_install.html#.npmInstall and here http://yeoman.io/authoring/dependencies.html

**Comment by Noviny** [comment]
Cleaning up the issues track, so closing this for now. We're going to keep updating manually until we have a clear solution to implement.
