### ISSUE TITLE
Editing keystone.js (and others) in any way results in jshint warning that aborts due to warnings...

### ISSUE THREAD

**Issue by PowrSlave** [keystonejs/generator-keystone#155]
If I try to, say, edit the path to a favicon in keystone.js and save it, then grunt watch chokes with the following warning: 

```javascript
Warning: Path must be a string. Received { toString: [Function], reporter: [Function] } Use --force to continue.

Aborted due to warnings.
```
If I undo the changes and save. The warning persists and grunt watch gives up. I'm a node newb, so help?

**Comment by briantschu** [comment]
@PowrSlave, I think you're experiencing the same issue represented in Issue #157.  Try the solution referenced, here: [updating **grunt/jshint.js**](https://github.com/keystonejs/generator-keystone/issues/157#issuecomment-195877628)

**Comment by mxstbr** [comment]
I'll close this since it seems solved!
