### ISSUE TITLE
grunt serve fails with warning

### ISSUE THREAD

**Issue by ghoshbinayak** [keystonejs/generator-keystone#157]
Running `grunt serve` or `grunt lint` results in the following error.

`Warning: Path must be a string. Received { toString: [Function], reporter: [Function] } Use --force to continue.

 `

**Comment by briantschu** [comment]
This error can be resolved by updating **grunt/jshint.js**. 

Enclose the options inside a globals object, like so:

```
	options: {
		globals: {
			reporter: require('jshint-stylish'),
			force: true
		},
	},
```
I created a pull request to update this syntax in the generator.

**Comment by ghoshbinayak** [comment]
@briantschu thanks! that fixed it.

**Comment by JedWatson** [comment]
Thanks @briantschu! Will publish an update with your fix now.
