### ISSUE TITLE
Cannot find module 'unicode/category/So' yo generator

### ISSUE THREAD

**Issue by sachingill** [keystonejs/generator-keystone#162]
facing below issue while running yeoman generator on windows.

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'unicode/category/So'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at symbols (E:\projects\keystoneapp\node_modules\slug\slug.js:6:16)
    at E:\projects\keystoneapp\node_modules\slug\slug.js:199:5
    at Object.<anonymous> (E:\projects\keystoneapp\node_modules\slug\slug.js:212
:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by sachingill** [comment]
resolved: 
solution: need to remove unicode module and reinstalled it.

**Comment by mxstbr** [comment]
:+1: glad to hear you resolved the issue!

**Comment by morenoh149** [comment]
I keep hearing a lot about this unicode dependency acting up. Any idea why?

**Comment by mxstbr** [comment]
_shrugs_ maybe @webteckie knows?

**Comment by webteckie** [comment]
Installing in windows aometimes is a real pain :-)  Not sure about this one...usually removing node_modules and reinstalling works...

**Comment by ppiekarczyk** [comment]
I've been meaning to write an article about this and I finally did:

https://medium.com/@ppskeet/handling-funky-unicode-issues-in-keystonejs-and-possible-other-node-related-projects-806a25846e0b#.gm6ltllje

**Comment by rajendrakhabiyagate6** [comment]
If you are facing this issue and you are behind windows please follow below steps, i hope worked for you :

 1. Remove the unicode module using npm, npm remove unicode
 2. Downloaded the file from
    http://unicode.org/Public/UNIDATA/UnicodeData.txt and placed it into
    C:\usr\share\unicode-data\ if your project is in C drive, or if you are in
    linux /usr/share/unicode or /usr/share/unicode-data 
 3. Installed unicode again
