### ISSUE TITLE
Update jade to pug

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/generator-keystone#169]
name changed https://github.com/pugjs/pug/issues/2184

**Comment by smedegaard** [comment]
I would label this as critical in stead of "help wanted"

**Comment by lifehome** [comment]
Hmm, is there any updates on this?

**Comment by jstockwin** [comment]
@lifehome See the corresponding issue on [keystonejs/keystone](https://github.com/keystonejs/keystone/issues/2610) - "this is nothing we can fix just yet."
We are waiting on a pug 2.0.0 release.

**Comment by JedWatson** [comment]
Pug has hit 2.0.0-beta3 so hopefully we'll be ready to do this soon :)

**Comment by waaronking** [comment]
Pug was [released in August](https://pugjs.org/api/migration-v2.html). Anyone working on this or still looking for help?

**Comment by bjwyse** [comment]
Haven't tested but I see https://github.com/keystonejs/generator-keystone/pull/224 which I assume would fix this.

**Comment by Noviny** [comment]
Closing this as using pug is now in master
