### ISSUE TITLE
how about including front-end framework and choosing bootstrap options?

### ISSUE THREAD

**Issue by the6thm0nth** [keystonejs/generator-keystone#17]
1. I was thinking that view api couldn't give a enough controller even if it has very awesome apis such as 'init' or render or 'restful'.
   But Some heavy sites need more events such as click or others like that.
   So, how about giving a choice to include a front-end framework( angular or backbone ) or not. It could be a issue about original Keystone itself.
2. (it also could be a issue about original Keystone itself). How about giving a choice bootstrap or not? there are so many times I want to use other framewokrs not bootstrap (using bower can be a great option).

Thank you!

**Comment by morenoh149** [comment]
@JedWatson we should revisit this in the future. metroui & zurb foundation are other options as well.

**Comment by JedWatson** [comment]
Agreed.

**Comment by Noviny** [comment]
We're trying to make the generator less opinionated not more, so we want to be very careful adding more things like this in.

Closing this issue. Feel free to reopen if you want to have further discussion about this.
