### ISSUE TITLE
Default hbs blog page displayed extended content

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/generator-keystone#171]
The [default handlebars template](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/templates/default-hbs/views/blog.hbs#L15) for the blog page displays the extended content, as well as a "read more" link which is essentially redundant. 

The [jade template](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/templates/default-jade/views/blog.jade#L21) instead displays the brief content, and if the extended content is present it gives a "read more" link. 

I feel the handlebars template should do the same. Happy to PR a fix, but please say if this is intended.

**Comment by mxstbr** [comment]
Fixed by @jstockwin in #172!
