### ISSUE TITLE
KeystoneJS watch:lint is not in your gulpfile

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/generator-keystone#193]
> Hello. I have the same issue as this guy described in this SO thread http://stackoverflow.com/questions/37205321/keystonejs-watchlint-is-not-in-your-gulpfile . How can I fix this?

**Comment by pll33** [comment]
It looks like the watch:lint mention wasn't taken out after 76da98bb removed jshint from both the grunt and gulpfiles. PR coming up in a bit

@JedWatson I'm not really familiar with jshint on this project, what was the reason for taking it out?

**Comment by morenoh149** [comment]
I think the community is using eslint now as a successor to jshint.

**Comment by pll33** [comment]
ah I noticed eslint files in the root. Is the next step to add eslint to gulp/grunt?

**Comment by morenoh149** [comment]
sure. Thought that's not high priority.

**Comment by JedWatson** [comment]
Fixed - we have added a `lint` task to npm, and cleaned up the remaining references to jslint. I think that's sufficient.
