### ISSUE TITLE
Add support for custom models

### ISSUE THREAD

**Issue by stennie** [keystonejs/generator-keystone#2]
As suggested by @JedWatson in [Keystone #88](https://github.com/JedWatson/keystone/issues/88#issuecomment-31835457), add support for generating custom models.

eg:

```
key? Post
fields? title String, content Html wysiwyg:true, published:Boolean, author Relationship ref:User
autokey? from:title key:slug unique:true
map? name:title
```

**Comment by Noviny** [comment]
Closing this as an old discussion.

If this is still something we want to discuss, feel free to reopen and comment.
