### ISSUE TITLE
Installation failed with "yo keystone"

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/generator-keystone#200]
> Expected behavior
> 
> I was following the "Get Started" page, "Commands". I wanted to install the latest version of keystone and startup new project.
> 
> Actual behavior
> 
> After the keystone-generator installed, tried to do "yo keystone" and the installation has started but it does not generate the project. I got the following error:
> 
> screen shot 2016-05-24 at 10 21 49
> 
> Thanks for helping me out!

**Comment by pll33** [comment]
Issue was fixed with #195, the Gruntfile is out of date on the 0.3.16 with npm install

@mxstbr
