### ISSUE TITLE
Sending emails with twig

### ISSUE THREAD

**Issue by r3wt** [keystonejs/generator-keystone#207]
After examing `_keystone.js` more closely, it appears i missed a step in my twig commits. I'm not sure how the email class works in keystone, but based on the implementation of handlebars, is the following code enough to allow keystone to send emails with twig?

``` js
<% if (viewEngine === 'twig') { %>
<% if (includeGuideComments) { %>
// Switch Keystone Email defaults to Twig.js
<% } %>
keystone.Email.defaults.templateExt = 'twig';
keystone.Email.defaults.templateEngine = Twig.render;
<% } %>
```

Relevant Keystone Issue: https://github.com/keystonejs/keystone/issues/3020

Its unclear to me if this will be enough. i'm having trouble reading the code in the email class and making sense of it.

**Comment by Noviny** [comment]
Closing this in favour of #234 as we need to overhaul the email in general
