### ISSUE TITLE
Remove Grunt and Gulp?

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/generator-keystone#210]
I'm looking for places we can simplify this generator, because its sprawling complexity is hurting our ability to keep it maintained and add new features.

One thing that's occurred to me is that we could remove the gulp and grunt implementations. The things they're doing could easily be handled by npm scripts (e.g. linting) and express middleware (e.g. less/sass/stylus compilation)

I think that if people want to add task runners to their projects, there are plenty of guides around to help get started and choose the best one without us supporting default configs for them all (e.g. I suspect webpack is more popular these days but we haven't got it)

Am I crazy? What do you all think of this?

**Comment by creynders** [comment]
At last 😉 
Opt-in not opt-out should be what we aim for, i.e. set up entry and end points to allow all kinds of integration, but cut out everything we can that's not 100% necessary.

**Comment by rogersillito** [comment]
sounds very sensible to me!

**Comment by chriswburke** [comment]
Agreed!

**Comment by Noviny** [comment]
PR for this has now been merged, closing issue.
