### ISSUE TITLE
Initiate Keystone views property from new Keystone installation 

### ISSUE THREAD

**Issue by A7bert** [keystonejs/generator-keystone#212]
Hi,

Not sure it is a new feature or a bug. When I tried to create a new Keystone project via generator-keystone.
In the keystone.js
`'views': ['templates', 'templates/views'],`
Why the views property is set to an array, but it should be a string?

Thanks

**Comment by JedWatson** [comment]
Good point @A7bert - I think #213 is the correct response to this :)

**Comment by brianjd** [comment]
@A7bert @JedWatson What is the issue with having an array?  Did it create a bug somewhere else?  Not having the array breaks consolidate/nunjucks.

**Comment by A7bert** [comment]
@brianjd , Keystone just can't initialize the views with an array value. It happens when I used the keystone-generator to create a new project. Why would it be an array?

**Comment by brianjd** [comment]
@A7bert Passing the array of `['templates', 'templates/views']` is a simple solution versus changing the view controller template references in the generator.

**Comment by brianjd** [comment]
@A7bert I am trying to better understand the issue you remedied, as the array has been working in my configuration in several production projects.  I was about to reintroduce the array in a PR fixing nunjucks for new projects.  So depending on the actual issue, I may have to rethink my approach.

**Comment by A7bert** [comment]
@brianjd , thank you for the explanation. I haven't used in nunjucks, but jade or handlebars. I can see there is an exception for choosing nunjunk in the generator repo. 

I just did another test, but I still got the same problem for a fresh keystone start. 
Sorry, an error occurred loading the page (500)
Path must be a string. Received [ 'templates', 'templates/views' ]
