### ISSUE TITLE
Error installing Generator

### ISSUE THREAD

**Issue by vickoman** [keystonejs/generator-keystone#215]
I have this issue when i try to install generator-keystone
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

**Comment by morenoh149** [comment]
warnings really aren't that big of a deal in my experience. Many times it's a problem with a dependency's dependency and there's little you can actually do yourself as you don't have control over those codebases.

**Comment by mxstbr** [comment]
Agreed, this is not an error but a warning. Thanks for the heads up though @vickoman!
