### ISSUE TITLE
ES6?

### ISSUE THREAD

**Issue by tylerFowler** [keystonejs/generator-keystone#216]
This would be a nice option, I just set up the first project I plan on using Keystone for and had to go through and ES6-ify everything. It only went south when changing the User model's `canAccessKeystone` field to a anon function due to the changed context of `this`. But of course I'm on Node 6.3.0 so it wouldn't work out as well for everyone.

Also on a lesser note, options for tabs vs spaces :wink: luckily Atom has a tabs -> spaces converter.

**Comment by Noviny** [comment]
We want to get out a version with keystone 4 that is node 0.12 compatible. Once we have a Keystone 4 version out, we will be updating the codebase for es6. 🙂

**Comment by MicahMartin** [comment]
Any updates on this? It'd be nice to have an es6 generator for keystone

**Comment by Noviny** [comment]
@MicahMartin No update, unfortunately. Still getting KS4 out.

**Comment by gautamsi** [comment]
its taking forever 😢

**Comment by gautamsi** [comment]
in the meanwhile I have converted generator code to TypeScript if anyone is interested. https://github.com/gautamsi/generator-keystone-ts.
