### ISSUE TITLE
Different Folder Structure between mac and ubuntu

### ISSUE THREAD

**Issue by sitompul** [keystonejs/generator-keystone#221]
I was pulling the code which was developed on ubuntu. The **/keystone** folder doesn't have cloudinary folder, and all keystone dependencies, instead all of them was stored at **/node_modules** folder. This will throw missing modules error when i try to add `var cloudinary = keystone.cloudinary`, instead i was forced to use `require('cloudinary').`

When i try to have clean install on ubuntu, it still creates the same **keystone** folder without the dependencies inside it.

Meanwhile when i npm install keystone on mac, it will create all the dependencies under **/keystone/node_modules** folder

I can fix this by changing the code, but it would be nice,if you have a solution for this.

**Comment by JedWatson** [comment]
This sounds like a difference between npm 3 and 4 / yarn, where npm 4 started flattening dependencies up as high as they would go.

`keystone.cloudinary` wouldn't work in either scenario (node side), the only place that exists is in the Admin UI Client on the window where we put the cloudinary options.

Short answer, I'd always recommend using `require('cloudinary')` in your own project, and explicitly defining the dependency in your project's `package.json`
