### ISSUE TITLE
node-sass not found

### ISSUE THREAD

**Issue by trentontri** [keystonejs/generator-keystone#227]
### Steps to reproduce the behavior
when I first run `yo keystone` followed by `node keystone` this is what I see:
Please install the node-sass-middleware from npm to use the `sass` option.
You can do this by running "npm install node-sass-middleware --save".

**Comment by TaylorAckley** [comment]
I believe this issue can be closed.    From latest, `node-sass-middleware` is in the `package.json` file and gets installed with `npm install`

**Comment by Noviny** [comment]
@TaylorAckley is right, this is included in the latest version of the generator.
