### ISSUE TITLE
Error: Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [keystonejs/generator-keystone#239]
Hi,
Please help me I'm not able to start the application I'm getting below error while running **node keystone**
Error: Cannot find module '../build/Release/bson'
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by Noviny** [comment]
This is a known error in keystone 3. See the discussion at: https://github.com/keystonejs/keystone/issues/1752

This should be resolved when we update to keystone 4.
