### ISSUE TITLE
no gulp/grunt option

### ISSUE THREAD

**Issue by juan-ruiz** [keystonejs/generator-keystone#249]
i just installed the keystone generator and when i run it i get no option for installing gulp/grunt, is there a different version? i did install generator-keystone

**Comment by Noviny** [comment]
Hi @juan-ruiz, sorry for the confusion. We removed gulp and grunt as features that the generator is supporting as of v0.5.0. Sorry this hasn't been clearly indicated!

If you can, can you tell me what documentation still mentioned the gulp and grunt feature?

**Comment by juan-ruiz** [comment]
not really official sources, i saw it on independent blogs and youtube channels, thanks for the heads up anyway! a notification of this on the release notes would be fine!

Again, thanks!

**Comment by Noviny** [comment]
We've just started formatting them here, but you can find our release notes [here](https://github.com/keystonejs/generator-keystone/blob/master/HISTORY.md).
