### ISSUE TITLE
sass files don't compile when switching from less

### ISSUE THREAD

**Issue by johnnyluu** [keystonejs/generator-keystone#250]
I set the project up with less chosen as the default css preprocessor, but now we've decided to use sass instead. I replaced 'less' with 'sass' in keystone.js, and installed node-sass and node-sass-middleware, but the sass files are just not getting compiled.

I tried starting a new project with sass set as default, that worked fine. Then I created another new project with less as default, then tried to switched to sass, it didn't compile either, so it's not likely related to the actual app I've written. Any idea why this is happening?

**Comment by Noviny** [comment]
Hi @johnnyluu , the sass file compiles down to `site.css`, while for less, this compiles down to `site.min.css`. If you look in `templates/layouts/default`, you can find where the file is referenced. You need to repoint this folder when making the switch.

**Comment by johnnyluu** [comment]
Thanks, I worked
