### ISSUE TITLE
post.js invalid limit param

### ISSUE THREAD

**Issue by wisetwo** [keystonejs/generator-keystone#255]
Code of this file, line 35:
https://github.com/keystonejs/generator-keystone/blob/master/app/templates/routes/views/post.js#L35

```
var q = keystone.list('Post').model.find().where('state', 'published').sort('-publishedDate').populate('author').limit('4');
```
Should `limit('4')` be replaced with `limit(4)`? Providing param with string won't work as expected, it seems.

**Comment by Noviny** [comment]
Fixed by @cooperxiong in #263
