### ISSUE TITLE
Outdated documentation url in _keystone.js comments

### ISSUE THREAD

**Issue by sjgllghr** [keystonejs/generator-keystone#278]
Minor issue.

https://github.com/keystonejs/generator-keystone/blob/d4c08487746d105800397d4e57c219188475ca25/app/templates/_keystone.js#L12-L14

http://keystonejs.com/guide/config goes to a "Whoops! Nothing to see here" page,
https://keystonejs.com/documentation/configuration/ seems to be the current location.

**Comment by stennie** [comment]
@sjgllghr Thanks for reporting .. there are a few urls in need of a refresh for Keystone v4. Will fix these by way of #279.

In the interim I've added a redirect for this url to the v4 equivalent so you'll no longer get a "whoops" 404 page.

Regards,
Stennie
