### ISSUE TITLE
how to support PostgreSQL instead of  MongoDB 

### ISSUE THREAD

**Issue by QianDingwei** [keystonejs/generator-keystone#290]
Recently I get a require to init a project using keystone and PostgreSQL.so,I want to know dose this package support PostgreSQL or How to support PostgreSQL

**Comment by Noviny** [comment]
Hey! This project is for keystone 4 which doesn't support postgres. keystone 5, which is a complete rebuild, supports it. I'd recommend checking out its starter.

https://github.com/keystonejs/keystone
