### ISSUE TITLE
Cookie secret should not be commited to the repo

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/generator-keystone#39]
I've noticed some people not hiding it, which means we probably shouldn't generate it into the `keystone.js` file. Maybe `.env` would be a better home for it... or we should at least add a warning comment above it.

**Comment by ericelliott** [comment]
:+1:

**Comment by morenoh149** [comment]
actually looks like this was solved previously by using the default cookie secret in keystone https://github.com/keystonejs/generator-keystone/commits/master/app/templates/_keystone.js specifically https://github.com/keystonejs/generator-keystone/commit/616cb7f5cd3a32e41c0ec838f4b873ad372269c3
