### ISSUE TITLE
Add an option for Coffeescript

### ISSUE THREAD

**Issue by rubenvereecken** [keystonejs/generator-keystone#48]
So how about coffeescript? I'm completely addicted to it and I think coffeescript would go great with keystone. I just tried out the basics for porting in my own projected, generated using this keystone generator. `keystone.js` is now a simple file importing coffeescript and a `setup.coffee` file which contains the coffee-fied of the original setup. The server can be easily translated. 

The only bit I'd be unsure about is the client-side, as we'd preferably need some pretty way to separate the coffeescript and javascript. Or is it possible to just compile all coffeescript into one big javascript file and use that for keystone? I don't know, I'm completely new to it.

Any thoughts would be appreciated or maybe cries from fellow coffeescript enthusiasts. I could attempt this option myself (New to Yeoman but that'll work out) but if someone could nudge me in the right directions that'd be great.

**Comment by jahbini** [comment]
Any progress on this?

**Comment by rubenvereecken** [comment]
Not at all actually, in the end I felt building a new generator was too much work.

**Comment by JedWatson** [comment]
I'm going to close this, nearly a year on since my last comment and I'm still not keen on adding another set of templates to the generator. Anyone is welcome to take the work here and create another community-contributed package as @grabbou suggested!

**Comment by JedWatson** [comment]
(p.s. knowing the work it takes to maintain generators, I'd actually discourage this, especially given that ES6 is rapidly become a viable thing and brings a lot of the benefits of coffeescript with it, but that's up to whoever is interested in taking this on)
