### ISSUE TITLE
Clean up the email templates (excl. the Jade ones)

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/generator-keystone#61]
The email templates have been ported from Jade to other languages without proper understanding of how they work, meaning they're quite broken at the moment.

The layout that the jade email templates extend is actually contained within keystone itself, not the default layout used for the site.

The markup is also a mixture of jade variables and mail chimp / mandrill variables, that are bound to the current Email implementation in Keystone.

This whole mess needs to be worked out, cleaned up, and documented.

**Comment by morenoh149** [comment]
so jade and nunjucks are working. Swig and Handlebars are not?

**Comment by Noviny** [comment]
We need to redo the emails, so closing this in favour of #234.
