### ISSUE TITLE
Many "WARN unmet dependency" when I use "npm install -g generator-keystone"

### ISSUE THREAD

**Issue by sjfkai** [keystonejs/generator-keystone#64]
[root@localhost keystone]# npm install -g generator-keystone
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/insight requires chalk@'~0.4.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/file-utils requires glob@'~3.2.6' but will load
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/findup-sync requires glob@'~3.2.9' but will load
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yosay/node_modules/strip-ansi requires ansi-regex@'^0.1.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yosay/node_modules/ansi-regex,
npm WARN unmet dependency which is version 0.2.1
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yosay/node_modules/taketalk requires minimist@'^0.1.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/yo/node_modules/yosay/node_modules/minimist,
npm WARN unmet dependency which is version 0.2.0
generator-keystone@0.2.5 /usr/lib/node_modules/generator-keystone
?..? colors@0.6.2
?..? lodash@2.4.1
?..? keystone-utils@0.1.12 (html-stringify@0.0.2, underscore@1.7.0, i@0.3.2)
?..? yeoman-generator@0.17.6 (dargs@2.0.3, diff@1.0.8, class-extend@0.1.1, rimraf@2.2.8, text-table@0.2.0, mime@1.2.11, async@0.9.0, isbinaryfile@2.0.1, github-username@1.0.0, run-async@0.1.0, shelljs@0.3.0, nopt@3.0.1, cross-spawn@0.2.3, grouped-queue@0.3.0, mkdirp@0.5.0, debug@1.0.4, chalk@0.5.1, iconv-lite@0.4.4, findup-sync@0.1.3, glob@4.0.5, underscore.string@2.3.3, file-utils@0.2.1, gruntfile-editor@0.2.0, request@2.42.0, cheerio@0.17.0, inquirer@0.7.1, download@1.0.7)
[root@localhost keystone]# yo keystone
-bash: yo: command not found

**Comment by poliveira89** [comment]
I have the same problem this happens because the usage of `peerDependencies`on generator-keystone.
On this generator `package.json` it's required `yo@1.0.0` as me you should have a different version of `yo`. So after you "installing" this generator this errors appears on `npm list`.
