### ISSUE TITLE
Choosing gulp as task runner breaks the generator

### ISSUE THREAD

**Issue by chrisnicotera** [keystonejs/generator-keystone#87]
Looks like gulp never published (or removed) higher than 3.6.2 from the registry. The generator is expecting at least 3.6.4, which doesn't exist and subsequently fails upon attempted install.

**Comment by chrisnicotera** [comment]
Opened pull request #88, which upgrades to ~3.7.0

**Comment by JedWatson** [comment]
Published as `0.2.16`. Thanks!
