### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by anthonybrown** [keystonejs/generator-keystone#9]
getting this in terminal:
`npm ERR! peerinvalid The package yo does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-amdblah@0.2.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-angular@0.7.1 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-angular-fullstack@1.3.2 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-backbone@0.2.3 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-backbone-mocha@0.0.3 wants yo@>=1.1.2
npm ERR! peerinvalid Peer generator-backstrap@0.2.0 wants yo@>=1.0.0-rc.1
npm ERR! peerinvalid Peer generator-basics@0.2.4 wants yo@~1.0
npm ERR! peerinvalid Peer generator-bbapp@0.0.2 wants yo@>=1.0.0-rc.1
npm ERR! peerinvalid Peer generator-bestiario@0.2.1 wants yo@>=1.1.2
npm ERR! peerinvalid Peer generator-bootstrap@0.1.6 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-commonjs@0.0.7 wants yo@>=1.0.0-rc.1.1
npm ERR! peerinvalid Peer generator-cornelio@0.0.6 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-ember@0.8.3 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-generator@0.4.3 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-gruntfile@0.0.9 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-h5bp@0.1.7 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-jekyllrb@1.2.1 wants yo@>=1.0.4
npm ERR! peerinvalid Peer generator-jquery@0.0.9 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-karma@0.6.0 wants yo@>=1.0.0-rc.1.1
npm ERR! peerinvalid Peer generator-keystone@0.1.8 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-mobile@1.0.0-alpha.1 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-mocha@0.1.3 wants yo@>=1.0.0-rc.1.1
npm ERR! peerinvalid Peer generator-node-express@0.0.3 wants yo@>=1.0.0-rc.1
npm ERR! peerinvalid Peer generator-react-app@0.1.7 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-webapp@0.4.8 wants yo@>=1.0.0

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "generator-keystone"
npm ERR! cwd /Users/anthonybrown
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/anthonybrown/npm-debug.log
npm ERR! not ok code 0`

**Comment by poliveira89** [comment]
I think that #64 it's related to this one.
