### ISSUE TITLE
bootstrap glyphicons fonts path is wrong

### ISSUE THREAD

**Issue by freder** [keystonejs/generator-keystone#90]
according to [`bootstrap/_variables.scss`](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/public/styles-sass/bootstrap/bootstrap/_variables.scss#L83) the glyphicons fonts are expected to live in `<project_root>/public/fonts/bootstrap/` — however the generator puts them in `<project_root>/public/fonts/`.

**Comment by willm** [comment]
I tired to move them into /public/fonts/bootstrap but I still can't get them to work, It seems the browser doesn't even try to request the woff files (when looking in the network panel). Not sure how to debug this as I'm no css expert and new to sass.

**Comment by TheRoadSouth** [comment]
I had this same bug (using master v0.4). Changing the variable declarations to the following works:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("../fonts/glyphicons-halflings-regular.eot");
  src: url("../fonts/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"), url("../fonts/glyphicons-halflings-regular.woff2") format("woff2"), url("../fonts/glyphicons-halflings-regular.woff") format("woff"), url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"), url("../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular") format("svg"); }
```
