### ISSUE TITLE
possible npm version issue

### ISSUE THREAD

**Issue by theolampert** [keystonejs/generator-keystone#94]
Deploying a generated app from this generator on digital ocean with dokku failed for me unless I set a newer npm version explicitly in the package.json. Otherwise it will run into this https protocol issue https://github.com/npm/npm/issues/2119. I'm not sure if this is a dokku/docker issue or due to the way npm is set in the package.json. Same app will work fine deployed to heroku.

**Comment by morenoh149** [comment]
looks like it's optional https://docs.npmjs.com/files/package.json#engines what minimum npm version was required for your issue?

**Comment by theolampert** [comment]
I set it to minimum 2.1.18, worked fine after that. The other workaround in the referenced issue above of setting the registry to http in the npm config above also worked, so I guess it's an old bug in that version of npm?.
