### ISSUE TITLE
Error: could find module after "yo  keystone"

### ISSUE THREAD

**Issue by Yinear** [keystonejs/generator-keystone#95]
Lots of modules are not installed even I did "npm install".
They are not listed in the package.json

Such as cookie-jar, qs, oauth-sign,  hawk, aws-sign, http-signature and so on.

**Comment by Yinear** [comment]
I installed it on Win7,  in admin console.

**Comment by Yinear** [comment]
I add the lost modules manually to the package.json and it works. 

"cookie-jar": "~0.3.0",
      "qs": "~2.3.3",
      "oauth-sign": "~0.6.0",
      "hawk": "~2.3.1",
      "aws-sign": "~0.1.1",
      "http-signature": "~0.10.1",
      "tunnel-agent": "~0.4.0",
      "json-stringify-safe": "~5.0.0",
      "forever-agent": "~0.5.2",
      "form-data": "~0.2.0",
      "debug": "~2.1.1",
      "mime": "~1.2.11",
      "once": "~1.3.1",
      "xml2js": "~0.4.4",
      "stream-counter": "~1.0.0"

**Comment by macbroadcast** [comment]
:+1:

**Comment by morenoh149** [comment]
is a pull request needed that adds the missing modules to the `package.json` file? @Yinear if so could you handle that?

**Comment by snowkeeper** [comment]
@Yinear can you provide some more details?  The packages you listed are not dependencies of generator-keystone or keystone@0.2.40.

I ran `yo keystone` on  a fresh install of yo and generator-keystone on win7 with success, so I was not able to reproduce your errors there or after running `node keystone`.  

What is failing for you?  Is it `yo keystone` or runniing `node keystone` after yoeman completes?

**Comment by Yinear** [comment]
@snowkeeper @morenoh149 

It was failed on "node keystone"
I tried for another three times and this problem didn't happen.
I guess it's because I did yo keystone in a folder which was for another project.  There must be some hidden files I didn't delete in the folder.

I'm OK now.  Nothing need to be change.  I close this issue.

**Comment by Zerim** [comment]
Ran into this issue as well, where the "yo keystone" seemed to fail before it finished, and the project it created was missing a whole bunch of node modules.

It was on a freshly created directory, and I had just installed latest versions of Node and MongoDB.  Using OSX.  Going to try and run the generator again and see if it fixes it as it did for Yinear.
