### ISSUE TITLE
Error when handlebars used for generating

### ISSUE THREAD

**Issue by olhapi** [keystonejs/generator-keystone#98]
Got an error after try to start (node keystone) keystone with fresh generated KeystoneJS and Handlebars as a templating language. With Jade everything works fine. 
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

**Comment by puagardian** [comment]
Got almost the same error when generating keystone only with User model.

**Comment by jeffreypriebe** [comment]
The current generated KeystoneJS with Handlebars isn't all there. Issues:
 1. You may need to setup the templating engine yourself: https://github.com/keystonejs/keystone/issues/1441 
 2. There is no enquiry-notification.hbs template (https://github.com/keystonejs/generator-keystone/pull/119)

I also encountered an issue where the path to the template is wrong. It may be the same https://github.com/keystonejs/generator-keystone/issues/110.
If you have this issue then, in addition to [ppiekarczyk](https://github.com/ppiekarczyk)'s workaround on [Issue 1441](https://github.com/keystonejs/keystone/issues/1441), you may also need to add to the keystone.Email options object passed in `templateBasePath: path.normalize(path.join(__dirname, '..', 'templates', 'views', 'emails'))`. All together:
```
new keystone.Email({
    templateExt: 'hbs',
    templateEngine: require('express-handlebars'),
    templateName: 'enquiry-notification'
    templateBasePath: path.normalize(path.join(__dirname, '..', 'templates', 'views', 'emails')),
```
