### ISSUE TITLE
Warning: Task "sass" not found. Use --force to continue.

### ISSUE THREAD

**Issue by hatzipanis** [keystonejs/generator-keystone#99]
I generated a new Keystone project using Sass but received this error after I ran `grunt serve` and re-saved _variables.scss

````javascript
>> File "public/styles/site/_variables.scss" changed.
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
````
Everything, to me, looks normal and Grunt should be running fine. And I couldn't find any other related issues here. Any ideas?

**Comment by morenoh149** [comment]
Both the `sass` and `watch` tasks are missing. https://github.com/keystonejs/generator-keystone/blob/master/app/templates/Gruntfile.js#L33 Must've been an oversight. @hatzipanis if you implement the missing tasks please push them upstream.

**Comment by hatzipanis** [comment]
Hmm, still getting my head around Grunt. Aren't the `sass` and `watch` tasks being called in from sass.js and watch.js respectively? `watch` is working fine too. I feel like we're missing the Grunt plugin? What should we be using here to compile our Sass?

**Comment by morenoh149** [comment]
take a look at https://github.com/keystonejs/generator-keystone/blob/master/app/templates/_package.json which task runner did you choose during the generator process? also https://www.npmjs.com/package/load-grunt-tasks

I didn't realize the tasks were in the `grunt` directory. And you're sure the watch task runs fine? perhaps grunt-load-tasks can't find sass.js

**Comment by hatzipanis** [comment]
> perhaps grunt-load-tasks can't find sass.js

That's what I thought but that wouldn't be consistent with the the other files which seem to be working fine. 

In the generator _package.json we don't include any Grunt x Sass plugin to match `sass` to. Installing sass-grunt fixes the errors and compiles correctly.

Not sure if I've gone about this the right way so maybe yourself and others can weigh in if this is the right solution.

**Comment by JedWatson** [comment]
Closed by #132

**Comment by FlavioTroja** [comment]
Fatal error: The implementation option must be passed to the Sass task

SOLVED: 
`npm install grunt-sass`

**Comment by Mano534** [comment]
i have the same problem when i work on a big website , please if any one know what is exactly the problem mean because the error doesnt have that much info
